### ISSUE TITLE
请问有没有兴趣开发JavaScript版ZLOGO?

### ISSUE THREAD

**Issue by nobodxbodon** [TKT2016/ZLanguage3#2]
希望你能主导或者参与. 想法来源: https://github.com/program-in-chinese/quan1/issues/1#issuecomment-348674791

一点初步设想, 参考ZLOGO的语言语法设计, 用JavaScript实现解释器(LOGO解释成Javascript), 然后调用p5js等绘图库进行绘制. 我正在尝试作一个技术验证的原型.

个人感觉好处是建一个静态网页的站点, 就可以供在线编程和学习. 再接下去如果有精力的话就可以开发后台建立代码库(用户库)等等, 促进代码分享.

**Comment by nobodxbodon** [comment]
验证原型在https://github.com/program-in-chinese/quan3. 演示了最简单的'前进xxx', 可以改动前进数量, 点击"运行"即可.

**Comment by TKT2016** [comment]
现在C#版的问题很很多，实在没有时间开发JavaScript版ZLOGO

**Comment by nobodxbodon** [comment]
最后[一篇](https://zhuanlan.zhihu.com/p/32571516)更新之后, 恐怕短期内不会继续了.
